name: Angular-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ändern Sie dies in Ihre gewünschte Node.js-Version

      - name: Install Angular project dependencies
        run: npm install
        working-directory: ./GUI

      - name: Build Angular Project
        run: npm run build
        working-directory: ./GUI

      - name: Run Angular Tests
        run: npm run test
        working-directory: ./GUI
